### PR TITLE
Prototyping

### PR DESCRIPTION
**Pull request by bigs**
Todo:

- [x] Add support to daemon for user configurable listen addrs (libp2p, not daemon control)
- [ ] Add a scenario runner to:
  - [x] Verify bootstrapping works
  - [ ] Execute test scenario
- [ ] Expose metric collection service
- [ ] Add metrics endpoint to daemon

### CODE REVIEW

**Comment by bigs** [comment]
I kind of messed up making a initial commit in master and branching everything off of that. Best to look at the entire state of the project in this branch.

**Comment by vasco-santos** [comment]
I got pretty confused with the PR differences. But then, I also checked the branch instead of the diff for better understanding.

From what I understood, this seems what I was expecting, being able to create a configurable topology for being used in tests scenarios. I will have a deeper look when you have a test scenario ready and I can try it out 👍

**Review by vasco-santos — COMMENTED** [review]
I got pretty confused with the PR differences. But then, I also checked the branch instead of the diff for better understanding.

From what I understood, this seems what I was expecting, being able to create a configurable topology for being used in tests scenarios. I will have a deeper look when you have a test scenario ready and I can try it out 👍

**Comment by jacobheun** [comment]
Are you just starting with go support and then we'll add js support once the basic functionality is there? I'm assuming this would eventually be part of the Deployment configuration?

**Comment by bigs** [comment]
@jacobheun regarding daemons, i'd like to make it JS compatible ASAP! what are the steps for installing/running the js daemon? just have node and do an npm install yeah? running in a chroot.

**Comment by bigs** [comment]
for the sake of having a more sane master, i'm going to merge as is and start proper feature branch development

**Pull request merged**
